import type { StudyItem } from "./study.functions";

// Banco offline: usado quando a IA está indisponível (sem créditos, sem conexão).
const BANK: { area: string; item: StudyItem }[] = [
  { area: "processual civil", item: { linha: "o juiz homologou os cálculos e extinguiu a execução por sentença", termo: "sentença", semantica: "Pronunciamento que, com fundamento nos arts. 485 ou 487 do CPC, põe fim à fase cognitiva ou extingue a execução (art. 203, §1º).", virada: { titulo: "Natureza do ato judicial", raciocinio: "A natureza de um ato judicial é definida pelo seu conteúdo (arts. 485/487 do CPC) e pela sua finalidade, jamais pelo nome que o juiz lhe deu.", exemplo: "\"Despacho: homologo os cálculos e dou por satisfeita a execução.\" Não é despacho, é sentença: cabe apelação. Quem agrava perde o prazo da apelação." } } },
  { area: "processual civil", item: { linha: "os prazos processuais contam apenas os dias úteis no novo código", termo: "prazo processual", semantica: "Lapso temporal para a prática de ato no processo; no CPC conta-se em dias úteis (art. 219).", virada: { titulo: "Prazo processual x prazo material", raciocinio: "O art. 219 do CPC só se aplica a prazos processuais. Prazos de direito material, como decadência e prescrição, correm em dias corridos.", exemplo: "O advogado conta em dias úteis os 120 dias do mandado de segurança (prazo decadencial, art. 23 da Lei 12.016) e impetra fora do prazo." } } },
  { area: "processual civil", item: { linha: "os embargos de declaração interrompem o prazo para outros recursos", termo: "embargos de declaração", semantica: "Recurso para sanar omissão, contradição, obscuridade ou erro material da decisão (art. 1.022 do CPC).", virada: { titulo: "Interrupção, não suspensão", raciocinio: "Embargos de declaração interrompem o prazo dos demais recursos (art. 1.026 do CPC): ele recomeça do zero. Desde 2015, isso vale também nos Juizados (art. 50 da Lei 9.099).", exemplo: "O advogado calcula só o saldo restante após os embargos e interpõe a apelação com dias de sobra que não precisava ter descartado — ou pior, acha que perdeu o prazo e desiste." } } },
  { area: "penal", item: { linha: "a atenuante não conduz a pena abaixo do mínimo legal na segunda fase", termo: "atenuante", semantica: "Circunstância legal que reduz a pena na segunda fase da dosimetria (arts. 65 e 66 do CP).", virada: { titulo: "Súmula 231 do STJ", raciocinio: "Na segunda fase, atenuantes não podem levar a pena abaixo do mínimo legal. Só as causas de diminuição (terceira fase) rompem o mínimo.", exemplo: "A defesa pede pena abaixo do mínimo pela confissão. Indeferido: o pedido correto era buscar uma minorante, como a tentativa ou o tráfico privilegiado." } } },
  { area: "processual penal", item: { linha: "no processo penal o prazo corre da intimação e não da juntada", termo: "intimação", semantica: "Ato de comunicação que dá ciência à parte de ato ou termo do processo.", virada: { titulo: "Súmula 710 do STF", raciocinio: "No processo penal, os prazos contam da data da intimação, e não da juntada aos autos do mandado ou carta precatória, ao contrário do processo civil.", exemplo: "O advogado acostumado ao CPC espera a juntada do mandado para contar o prazo da apelação criminal e o recurso é declarado intempestivo." } } },
  { area: "constitucional", item: { linha: "o governador precisa demonstrar pertinência temática na ação direta", termo: "pertinência temática", semantica: "Relação entre o objeto da ação de controle concentrado e os interesses institucionais do legitimado.", virada: { titulo: "Legitimados especiais (art. 103 da CF)", raciocinio: "Mesa de Assembleia, Governador, confederação sindical e entidade de classe de âmbito nacional são legitimados especiais e devem demonstrar pertinência temática. Os demais são universais.", exemplo: "Uma confederação sindical ajuíza ADI contra lei que não afeta sua categoria: a ação não é conhecida por falta de pertinência temática." } } },
  { area: "tributário", item: { linha: "a declaração do contribuinte constitui o crédito tributário declarado", termo: "crédito tributário", semantica: "Relação jurídica que confere ao Fisco o direito de exigir o tributo, constituída pelo lançamento (art. 142 do CTN).", virada: { titulo: "Súmula 436 do STJ", raciocinio: "A entrega da declaração reconhecendo o débito constitui o crédito, dispensando lançamento. A partir daí não se fala mais em decadência, mas em prescrição.", exemplo: "A defesa alega decadência de tributo declarado e não pago há seis anos. Tese errada: o correto é discutir prescrição, contada do vencimento ou da entrega." } } },
  { area: "administrativo", item: { linha: "o ressarcimento ao erário por improbidade dolosa é imprescritível", termo: "imprescritibilidade", semantica: "Qualidade da pretensão que não se extingue pelo decurso do tempo.", virada: { titulo: "Tema 897 do STF", raciocinio: "São imprescritíveis as ações de ressarcimento ao erário fundadas em ato doloso de improbidade. Para ilícitos civis comuns, há prescrição (Tema 666).", exemplo: "O advogado alega prescrição quinquenal contra cobrança de dano ao erário por fraude dolosa em licitação. A tese é rejeitada de plano." } } },
  { area: "civil", item: { linha: "os juros de mora fluem desde o evento danoso na responsabilidade extracontratual", termo: "juros moratórios", semantica: "Remuneração devida pelo atraso no cumprimento da obrigação.", virada: { titulo: "Súmulas 54 e 362 do STJ", raciocinio: "No ilícito extracontratual, juros correm do evento danoso (Súm. 54). A correção do dano moral corre do arbitramento (Súm. 362). No contratual, juros correm da citação.", exemplo: "Em acidente de trânsito, o advogado pede juros a partir da citação e perde anos de juros que eram devidos desde o acidente." } } },
  { area: "trabalho", item: { linha: "a prescrição trabalhista é bienal após a extinção do contrato", termo: "prescrição bienal", semantica: "Prazo de dois anos após a extinção do contrato para ajuizar a reclamação (art. 7º, XXIX, da CF).", virada: { titulo: "Bienal + quinquenal", raciocinio: "Há dois filtros: a ação deve ser proposta até dois anos após o fim do contrato, e só alcança os cinco anos anteriores ao ajuizamento, não à rescisão.", exemplo: "O empregado espera 23 meses para ajuizar: a ação é tempestiva, mas perde quase dois anos de verbas, pois os cinco anos contam do ajuizamento." } } },
  { area: "processual do trabalho", item: { linha: "sem o depósito recursal o recurso ordinário será considerado deserto", termo: "deserção", semantica: "Inadmissibilidade do recurso pela falta ou insuficiência do preparo.", virada: { titulo: "Depósito recursal (art. 899 da CLT)", raciocinio: "O depósito recursal garante o juízo e é pressuposto do recurso do empregador. Ele deve ser comprovado no prazo do recurso.", exemplo: "A empresa recorre e junta o comprovante do depósito dias depois do prazo: recurso deserto, condenação mantida." } } },
  { area: "consumidor", item: { linha: "o consumidor tem noventa dias para reclamar de vício em produto durável", termo: "vício do produto", semantica: "Defeito que torna o produto impróprio ou diminui seu valor, sem necessariamente causar dano à segurança.", virada: { titulo: "Vício (art. 26) x fato do produto (art. 27)", raciocinio: "Vício gera prazo decadencial de 30 ou 90 dias. Acidente de consumo (fato do produto) gera prazo prescricional de cinco anos.", exemplo: "A geladeira explode e fere o consumidor seis meses depois. Não houve decadência: é fato do produto, com cinco anos para a ação." } } },
  { area: "empresarial", item: { linha: "a desconsideração da personalidade jurídica exige abuso comprovado", termo: "desconsideração", semantica: "Afastamento episódico da autonomia patrimonial da pessoa jurídica para atingir bens dos sócios.", virada: { titulo: "Teoria maior x teoria menor", raciocinio: "No Código Civil (art. 50) exige-se desvio de finalidade ou confusão patrimonial. No CDC (art. 28, §5º) basta que a personalidade seja obstáculo ao ressarcimento.", exemplo: "Em execução cível comum, o credor pede desconsideração só por insolvência da empresa. Indeferido: sem abuso, não se aplica o art. 50." } } },
  { area: "ética", item: { linha: "os honorários de sucumbência pertencem ao advogado e não à parte", termo: "honorários sucumbenciais", semantica: "Verba fixada na sentença em favor do advogado do vencedor (art. 85 do CPC).", virada: { titulo: "Art. 23 do Estatuto da OAB", raciocinio: "Os honorários de sucumbência pertencem ao advogado, que pode executá-los autonomamente. Têm natureza alimentar (Súmula Vinculante 47).", exemplo: "O cliente faz acordo e renuncia aos honorários sucumbenciais do advogado. A renúncia não atinge o advogado, que pode cobrá-los." } } },
  { area: "criança", item: { linha: "a internação do adolescente não excede três anos em nenhuma hipótese", termo: "internação", semantica: "Medida socioeducativa privativa de liberdade, sujeita à brevidade e excepcionalidade (art. 121 do ECA).", virada: { titulo: "Limites da internação", raciocinio: "A internação não excede três anos, com reavaliação a cada seis meses, e a liberação é compulsória aos 21 anos (art. 121, §§ 2º, 3º e 5º).", exemplo: "O ato infracional foi grave e o juiz quer manter a internação por quatro anos. Ilegal: cabe habeas corpus." } } },
  { area: "previdenciário", item: { linha: "durante o período de graça o segurado mantém todos os seus direitos", termo: "período de graça", semantica: "Tempo em que a pessoa mantém a qualidade de segurado mesmo sem contribuir (art. 15 da Lei 8.213).", virada: { titulo: "Prorrogações do art. 15", raciocinio: "O período básico é de 12 meses, acrescido de 12 se houver mais de 120 contribuições sem perda da qualidade, e de mais 12 se comprovado desemprego.", exemplo: "O INSS nega pensão por morte alegando perda da qualidade após 14 meses sem contribuir. Com o desemprego comprovado, o segurado ainda estava coberto." } } },
  { area: "eleitoral", item: { linha: "as condições de elegibilidade são aferidas no momento do registro", termo: "elegibilidade", semantica: "Capacidade eleitoral passiva: aptidão para ser votado.", virada: { titulo: "Art. 11, §10, da Lei 9.504", raciocinio: "Elegibilidade é aferida na formalização do registro, ressalvadas alterações posteriores que afastem a inelegibilidade.", exemplo: "A condenação do candidato é suspensa por liminar após o registro: a alteração superveniente favorável pode ser considerada para deferir a candidatura." } } },
];

export function offlineStudy(area: string, count: number, seen: string[]): StudyItem[] {
  const a = area.toLowerCase();
  const matches = BANK.filter((b) => a.includes(b.area) || b.area.split(" ").every((w) => a.includes(w)));
  const pool = (matches.length ? [...matches, ...BANK.filter((b) => !matches.includes(b))] : [...BANK].sort(() => Math.random() - 0.5)).map((b) => b.item);
  const fresh = pool.filter((i) => !seen.includes(i.termo));
  const list = fresh.length >= count ? fresh : [...fresh, ...pool];
  return list.slice(0, count);
}
